<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\service\ConversationManager' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/service/ConversationManager.php';

return $this->privates['App\\service\\ConversationManager'] = new \App\service\ConversationManager(($this->privates['App\\Repository\\ConversationRepository'] ?? $this->load('getConversationRepositoryService.php')));
