vich_uploader:
    db_driver: orm

    mappings:
        document_file:
            uri_prefix: /uploads/documents
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load : false
            delete_on_update : true
            delete_on_remove : true

        picture_file:
            uri_prefix: /uploads/pictures
            upload_destination: '%kernel.project_dir%/public/uploads/pictures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

