<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJyM6PH2\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJyM6PH2/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJyM6PH2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJyM6PH2\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerJyM6PH2\srcApp_KernelProdContainer([
    'container.build_hash' => 'JyM6PH2',
    'container.build_id' => '59584d64',
    'container.build_time' => 1700738444,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJyM6PH2');
