<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPhyoLPG\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPhyoLPG/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPhyoLPG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPhyoLPG\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerPhyoLPG\srcApp_KernelProdContainer([
    'container.build_hash' => 'PhyoLPG',
    'container.build_id' => '03ffb135',
    'container.build_time' => 1700729008,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPhyoLPG');
