<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.uxumEEF' shared service.

return $this->privates['.service_locator.uxumEEF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'message' => ['privates', '.errored..service_locator.uxumEEF.App\\Entity\\Message', NULL, 'Cannot autowire service ".service_locator.uxumEEF": it references class "App\\Entity\\Message" but no such service exists.'],
    'user' => ['privates', '.errored..service_locator.uxumEEF.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.uxumEEF": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
], [
    'message' => 'App\\Entity\\Message',
    'user' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
]);
