<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine.dbal.default_connection' shared service.

include_once \dirname(__DIR__, 4).'/vendor/doctrine/dbal/src/Connection.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/ConnectionFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/dbal/src/Configuration.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/src/EventManager.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php';

$a = new \Doctrine\DBAL\Configuration();
$a->setMiddlewares([]);
$b = new \Symfony\Bridge\Doctrine\ContainerAwareEventManager(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'doctrine.orm.default_listeners.attach_entity_listeners' => ['privates', 'doctrine.orm.default_listeners.attach_entity_listeners', 'getDoctrine_Orm_DefaultListeners_AttachEntityListenersService.php', true],
    'vich_uploader.listener.clean.document_file' => ['privates', 'vich_uploader.listener.clean.document_file', 'getVichUploader_Listener_Clean_DocumentFileService.php', true],
    'vich_uploader.listener.clean.picture_file' => ['privates', 'vich_uploader.listener.clean.picture_file', 'getVichUploader_Listener_Clean_PictureFileService.php', true],
    'vich_uploader.listener.remove.document_file' => ['privates', 'vich_uploader.listener.remove.document_file', 'getVichUploader_Listener_Remove_DocumentFileService.php', true],
    'vich_uploader.listener.remove.picture_file' => ['privates', 'vich_uploader.listener.remove.picture_file', 'getVichUploader_Listener_Remove_PictureFileService.php', true],
    'vich_uploader.listener.upload.document_file' => ['privates', 'vich_uploader.listener.upload.document_file', 'getVichUploader_Listener_Upload_DocumentFileService.php', true],
    'vich_uploader.listener.upload.picture_file' => ['privates', 'vich_uploader.listener.upload.picture_file', 'getVichUploader_Listener_Upload_PictureFileService.php', true],
], [
    'doctrine.orm.default_listeners.attach_entity_listeners' => '?',
    'vich_uploader.listener.clean.document_file' => '?',
    'vich_uploader.listener.clean.picture_file' => '?',
    'vich_uploader.listener.remove.document_file' => '?',
    'vich_uploader.listener.remove.picture_file' => '?',
    'vich_uploader.listener.upload.document_file' => '?',
    'vich_uploader.listener.upload.picture_file' => '?',
]), [0 => 'vich_uploader.listener.clean.document_file', 1 => 'vich_uploader.listener.clean.picture_file', 2 => 'vich_uploader.listener.remove.document_file', 3 => 'vich_uploader.listener.upload.document_file', 4 => 'vich_uploader.listener.remove.picture_file', 5 => 'vich_uploader.listener.upload.picture_file']);
$b->addEventListener([0 => 'loadClassMetadata'], 'doctrine.orm.default_listeners.attach_entity_listeners');

return $this->services['doctrine.dbal.default_connection'] = (new \Doctrine\Bundle\DoctrineBundle\ConnectionFactory([]))->createConnection(['driver' => 'pdo_mysql', 'charset' => 'utf8mb4', 'url' => $this->getEnv('resolve:DATABASE_URL'), 'host' => 'localhost', 'port' => NULL, 'user' => 'root', 'password' => NULL, 'driverOptions' => [], 'serverVersion' => '5.7', 'defaultTableOptions' => ['charset' => 'utf8mb4', 'collate' => 'utf8mb4_unicode_ci']], $a, $b, []);
