<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Vich\UploaderBundle\Twig\Extension\UploaderExtensionRuntime' shared service.

include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/vich/uploader-bundle/src/Twig/Extension/UploaderExtensionRuntime.php';
include_once \dirname(__DIR__, 4).'/vendor/vich/uploader-bundle/src/Templating/Helper/UploaderHelperInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/vich/uploader-bundle/src/Templating/Helper/UploaderHelper.php';

return $this->privates['Vich\\UploaderBundle\\Twig\\Extension\\UploaderExtensionRuntime'] = new \Vich\UploaderBundle\Twig\Extension\UploaderExtensionRuntime(new \Vich\UploaderBundle\Templating\Helper\UploaderHelper(($this->privates['vich_uploader.storage.file_system'] ?? $this->load('getVichUploader_Storage_FileSystemService.php'))));
