<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4V7yqKg' shared service.

return $this->privates['.service_locator.4V7yqKg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'conversationRepo' => ['privates', 'App\\Repository\\ConversationRepository', 'getConversationRepositoryService.php', true],
], [
    'conversationRepo' => 'App\\Repository\\ConversationRepository',
]);
