<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.1Bvml7A' shared service.

return $this->privates['.service_locator.1Bvml7A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'conversationManager' => ['privates', 'App\\service\\ConversationManager', 'getConversationManagerService.php', true],
    'conversationRepo' => ['privates', 'App\\Repository\\ConversationRepository', 'getConversationRepositoryService.php', true],
    'document' => ['privates', '.errored..service_locator.1Bvml7A.App\\Entity\\Document', NULL, 'Cannot autowire service ".service_locator.1Bvml7A": it references class "App\\Entity\\Document" but no such service exists.'],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
], [
    'conversationManager' => 'App\\service\\ConversationManager',
    'conversationRepo' => 'App\\Repository\\ConversationRepository',
    'document' => 'App\\Entity\\Document',
    'userRepository' => 'App\\Repository\\UserRepository',
]);
