<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fQeCS3r' shared service.

return $this->privates['.service_locator.fQeCS3r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'documentRepository' => ['privates', 'App\\Repository\\DocumentRepository', 'getDocumentRepositoryService.php', true],
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
], [
    'documentRepository' => 'App\\Repository\\DocumentRepository',
    'paginator' => '?',
]);
