<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.U28rs3b.App\Entity\Conversation' shared service.

$this->throw('Cannot autowire service ".service_locator.U28rs3b": it references class "App\\Entity\\Conversation" but no such service exists.');
