<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mailer.mailer' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/MailerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Mailer.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Transport/TransportInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Transport/Transports.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Transport.php';

return $this->privates['mailer.mailer'] = new \Symfony\Component\Mailer\Mailer((new \Symfony\Component\Mailer\Transport(new RewindableGenerator(function () {
    yield 0 => $this->load('getMailer_TransportFactory_GmailService.php');
    yield 1 => $this->load('getMailer_TransportFactory_NullService.php');
    yield 2 => $this->load('getMailer_TransportFactory_SendmailService.php');
    yield 3 => $this->load('getMailer_TransportFactory_SmtpService.php');
}, 4)))->fromStrings(['main' => $this->getEnv('MAILER_DSN')]), NULL, ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
