<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'vich_uploader.download_handler' shared service.

include_once \dirname(__DIR__, 4).'/vendor/vich/uploader-bundle/src/Handler/AbstractHandler.php';
include_once \dirname(__DIR__, 4).'/vendor/vich/uploader-bundle/src/Handler/DownloadHandler.php';

return $this->services['vich_uploader.download_handler'] = new \Vich\UploaderBundle\Handler\DownloadHandler(($this->privates['vich_uploader.property_mapping_factory'] ?? $this->load('getVichUploader_PropertyMappingFactoryService.php')), ($this->privates['vich_uploader.storage.file_system'] ?? $this->load('getVichUploader_Storage_FileSystemService.php')));
