<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKdhxlsy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKdhxlsy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKdhxlsy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKdhxlsy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKdhxlsy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Kdhxlsy',
    'container.build_id' => 'ba6310b8',
    'container.build_time' => 1700728033,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKdhxlsy');
